AllCops:
  Exclude:
    - Guardfile
    - spec/spec_helper.rb
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
